service: python-sandbox

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: '*'
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: arn:aws:ses:ap-northeast-1:*:identity/*
  

functions:
  sndEmailWithAttachment:
    handler: functions.sendEmailWithAttachment.lambda_handler
    environment:
      SENDER_EMAIL: ${ssm:/serverless/framework/sandbox/python/ses/domain}
      RECIPIENT_EMAIL: ${ssm:EMAIL}

plugins:
  - serverless-python-requirements
