service: python-sandbox

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1

functions:
  sndEmailWithAttachment:
    handler: functions.sndEmailWithAttachment.lambda_handler

plugins:
  - serverless-python-requirements
